spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '12345'
    username: root
    url: jdbc:mysql://localhost:3306/mobileleGO?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#    properties:
#      format_sql : 'TRUE'
#      show_sql : 'TRUE'

#logging:
#  level:
#    org:
#      hibernate:
 #       type:
 #         descriptor: TRACE
 #       SQL: DEBUG
 #     nodeValue: WARN
#    blog: WARN

#server:
#  port: '8008'
